---
version: "2.0"

services:
  mongo:
    image: mongo:latest 
    expose:
      - port: 27017 
        to:
          - global: true
    env:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

profiles:
  compute:
    mongo:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 256Mi
        storage:
          size: 512Mi
  placement:
      pricing:
        mongo: 
          denom: uakt
          amount: 100

deployment:
  mongo:
    akash:
      profile: mongo
      count: 1 
